### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by amiltonwong** [tsattler/vps#1]
Hi, @tsattler ,

When the code be released ?

THX~

**Comment by tsattler** [comment]
Hi @amiltonwong ,

I currently can't answer this for certain. It depends on how much time I will have besides my regular job to clean up the code and remove dependencies from other parts of my library.

Best,
Torsten

**Comment by amiltonwong** [comment]
That's fine @tsattler . I can wait for it. :)

**Comment by linfan68** [comment]
@tsattler any update on this? ;-)

**Comment by tsattler** [comment]
Unfortunately not. It is hard for me to find time to work on the code due to my current workload.

**Comment by anonymous2792** [comment]
Hi @tsattler 

can I get any approximate idea, when the code will be released as it is around mid of 2018?

Thanks

**Comment by MohammadJalwana** [comment]
@tsattler, Looking forward to the code release. Can you please give us some update?

**Comment by tsattler** [comment]
I just finished my 10th business-related trip this year and haven't had time yet to work on the release of the code. I hope to find time within the next 1-2 months for this. I am sorry that the release is taking so long. However, this is something that I work on outside of my regular job.

**Comment by hairuiGo** [comment]
Looking forward to the code release. When the code be released ?

**Comment by tsattler** [comment]
I hope to find some time soon to work on the code release, but I am currently back to 60-70h working weeks.

**Comment by xiaoxiaobx** [comment]
Hi, @tsattler ,

When the code be released ?Looking forward to the code release.

**Comment by xiaoxiaobx** [comment]
Hi, @tsattler,
How can I not find GMM website in read.txt? Where can I download GMM.

**Comment by tsattler** [comment]
@xiaoxiaobx I plan to prepare the code for release once I get back to 9h working days. 

You can find GMM here: http://getfem.org/gmm/ or by searching for "gmm library" on Google.

**Comment by xiaoxiaobx** [comment]
Thank you.tsattler,
How can I download FLANN? How can't I find the URL? and very much Looking forward to the code release.

**Comment by imelekhov** [comment]
Hi @xiaoxiaobx,
You can find FLANN library [here](https://github.com/mariusmuja/flann).

**Comment by xiaoxiaobx** [comment]
> Hi @xiaoxiaobx,
> You can find FLANN library [here](https://github.com/mariusmuja/flann).
 Hi @imelekhov,
I want FLANN version 1.6.11 and How can I download LAPACK?

**Comment by tsattler** [comment]
@xiaoxiaobx You can find FLANN version 1.6.11 here: https://github.com/alexs7/ACG_Localizer
Installing LAPACK is a standard procedure on most Linux architecture. Please search the web for instructions on how to install it.

**Comment by ixtiyoruz** [comment]
happy new year. )))

**Comment by xiaoxiaobx** [comment]
Hi, @tsattler,
When I run the following command, the following error occurs. How to solve it ？
* compute_desc_assignments bundle.info 1 100000 clusters.txt                                                                    bundle.desc_assignments.integer_mean.kdtree.clusters.100k.bin 6 0 0
-> parsing the bundler output from bundle.info
--> done parsing the bundler output 
[Visual_Words_Handler]: ERROR: Cannot read the clusters from clusters.txt
 ERROR: Could not load the cluster centers from clusters.txt

**Comment by xiaoxiaobx** [comment]
Hi, @tsattler,
When I run the following command, the following error occurs. How to solve it? or how to find and generate clusters.txt ？

* compute_desc_assignments bundle.info 1 100000 clusters.txt                                                                    bundle.desc_assignments.integer_mean.kdtree.clusters.100k.bin 6 0 0
-> parsing the bundler output from bundle.info
--> done parsing the bundler output 
[Visual_Words_Handler]: ERROR: Cannot read the clusters from clusters.txt
 ERROR: Could not load the cluster centers from clusters.txt

**Comment by tsattler** [comment]
@xiaoxiaobx Please see the README.txt file for details on the files:
```
The next parameter specifies the number of visual words / cluster centers,
while "clusters.txt" is a text file containing those cluster centers. Any
clustering computed by k-means can be used as long as you make sure that you
compute the clustering on unnormalized SIFT descriptors similar to those
contained in the keypoint files. The computed cluster centers can then be
written into a text file, where the entries are separated by blanks and every
line contains one cluster center. 
```
and
```
An example cluster file containing 100k visual words can be found at
www.rwth-graphics.de/localization/.
```

**Comment by xiaoxiaobx** [comment]
@tsattler,&nbsp;
I see the README.txt file,but I can't get the corresponding clusters.txt.
and how to generate it by software or program? how can I computed cluster centers ?

Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Torsten Sattler"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 下午3:32
收件人:&nbsp;"tsattler/vps"<vps@noreply.github.com&gt;;
抄送:&nbsp;"专属bx"<775096562@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tsattler/vps] code release (#1)




@xiaoxiaobx Please see the README.txt file for details on the files:
 The next parameter specifies the number of visual words / cluster centers, while "clusters.txt" is a text file containing those cluster centers. Any clustering computed by k-means can be used as long as you make sure that you compute the clustering on unnormalized SIFT descriptors similar to those contained in the keypoint files. The computed cluster centers can then be written into a text file, where the entries are separated by blanks and every line contains one cluster center.   
and
 An example cluster file containing 100k visual words can be found at www.rwth-graphics.de/localization/.

**Comment by tsattler** [comment]
@xiaoxiaobx All the information you require are in my previous post: 
`
Any clustering computed by k-means can be used as long as you make sure that you
compute the clustering on unnormalized SIFT descriptors similar to those
contained in the keypoint files.
`
The vocabulary is available at www.rwth-graphics.de/localization/ (search for `The generic visual vocabulary used in the paper can be found here. The visual words are stored in a text file, with the first 128 floating point values describing the first word and so on.`).

**Comment by AsimJalwana** [comment]
@xiaoxiaobx , if you want to compute the clusters, you may use vlfeat (https://www.vlfeat.org/overview/kmeans.html), I used it long back. However, using the generic visual vocabulary which Torsten has pointed above works equally well.

**Comment by tsattler** [comment]
Another possibility is to use the Faiss library for clustering.

**Comment by xiaoxiaobx** [comment]
Hi ,tsattler

Thank you for your advice last time.
When I run acg_localizer, the intermediate results are as follows.Only a few results were written.Why does this happen? Which parameter is wrong? I've been looking for it for a long time.


--------- 1 / 11 --------- 
&nbsp;loaded 1290 descriptors from kermit000.key
&nbsp;assigned visual words in 0 minutes 0.007272 seconds&nbsp; to 1249 unique vw
&nbsp;computed correspondences in 0 minutes 6.7e-05 seconds , considering 1290 features 
&nbsp;applying RANSAC on 0 correspondences 
[RANSAC] Applying RANSAC on 0 correspondences 
[RANSAC] Applying RANSAC took 0 minutes 2e-06 seconds 
#### found solution ####
&nbsp;needed time: 0 minutes 9.2e-05 seconds 
&nbsp;camera calibration: [ nan, nan, nan ]
[ nan, nan, nan ]
[ nan, nan, nan ]

&nbsp;camera rotation: [ nan, nan, nan ]
[ -nan, -nan, -nan ]
[ nan, nan, nan ]

&nbsp;camera position: -nan -nan -nan
#########################






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Torsten Sattler"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 凌晨1:57
收件人:&nbsp;"tsattler/vps"<vps@noreply.github.com&gt;;
抄送:&nbsp;"专属bx"<775096562@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tsattler/vps] code release (#1)




Another possibility is to use the Faiss library for clustering.

**Comment by tsattler** [comment]
Hi @xiaoxiaobx, it seems that the program cannot find any matches. Without matches, it is impossible to estimate a camera pose.

**Comment by xiaoxiaobx** [comment]
Hi，@tsattler



Yes, I know, but now I want to know how to get the image data,
I would like to ask you, the image data of 3D reconstruction using bundle must be in your paper? Can I use other data, image reconstruction or my own data? And then use the visual vocabulary of clusters.txt to find and match?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Torsten Sattler"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 晚上8:21
收件人:&nbsp;"tsattler/vps"<vps@noreply.github.com&gt;;
抄送:&nbsp;"专属bx"<775096562@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tsattler/vps] code release (#1)




Hi @xiaoxiaobx, it seems that the program cannot find any matches. Without matches, it is impossible to estimate a camera pose.

**Comment by tsattler** [comment]
I don't know what you mean by image data.

You can use the software on other datasets as well. However, the software assumes that the coordinate system convention of Bundler is used (i.e., the camera is looking down the negative z-axis, with the y-axis pointing upwards, which is **not** the camera coordinate system typically used in computer vision). 
The visual vocabulary provided by me will only work for certain SIFT implementations (all those that produce similar results as SiftGPU), as mentioned in the readme file.

**Comment by xiaoxiaobx** [comment]
Hi,@tsattler I'm sorry to bother you again. I want to know where I'm wrong.


Here are my steps:

1. I use bundle for 3D reconstruction to get bundle.out,
2. Then get the bundles.info, the vocabulary（clusters.txt） is available at www.rwthgraphics.de/localization/ ,
3. Then run each executable program according to readme file. The previous one runs successfully,
4. When I run acg_localizer, no match is found.

Why can't we find a match? Can't we find it in the virtual vocabulary or is there a mistake in the 3D point of the result of 3D reconstruction?
Thank you ! 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Torsten Sattler"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 晚上8:21
收件人:&nbsp;"tsattler/vps"<vps@noreply.github.com&gt;;
抄送:&nbsp;"专属bx"<775096562@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tsattler/vps] code release (#1)




Hi @xiaoxiaobx, it seems that the program cannot find any matches. Without matches, it is impossible to estimate a camera pose.

**Comment by tsattler** [comment]
It's impossible to tell what happens if you don't provide details on what dataset you tried.

Potential things that could go wrong:
1. The SIFT implementation you used is not compatible with the SIFT method I used to create the visual vocabulary. I am not sure, but I think David Lowe's original binary used by Bundler is not compatible. Possible solution: Train the visual vocabulary yourself.
2. The visual vocabulary you are using is too large for the dataset. The one I released contains 100k words. If your dataset is small (e.g., just a few tens of thousand of points), this vocabulary is likely to be too fine and you should use one with fewer words.

I will close this issue now since it has gotten of topic.

If you are running into problems with the code, please open a new issue.
